import type { Product } from "./types"

export const completeProductsList: Product[] = [
  // Aluminium Doors and Windows Gasket (108 products)
  { id: "1", name: "SR-002", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-002.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "2", name: "SR-003", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-003.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "3", name: "SR-004", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-004.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "4", name: "SR-005", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-005.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "5", name: "SR-006", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-006.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "6", name: "SR-007", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-007.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "7", name: "SR-008", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-008.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "8", name: "SR-009", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-009.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "9", name: "SR-010", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-010.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "10", name: "SR-011", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-011.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "11", name: "SR-012", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-012.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "12", name: "SR-013", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-013.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "13", name: "SR-014", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-014.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "14", name: "SR-015", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-015.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "15", name: "SR-016", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-016.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "16", name: "SR-017", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-017.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "17", name: "SR-018", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-018.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "18", name: "SR-019", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-019.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "19", name: "SR-021", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-021.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "20", name: "SR-022", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-022.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "21", name: "SR-023", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-023.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "22", name: "SR-024", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-024.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "23", name: "SR-025", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-025.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "24", name: "SR-030", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-030.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "25", name: "SR-031", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-031.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "26", name: "SR-032", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-032.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "27", name: "SR-033", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-033.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "28", name: "SR-034", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-034.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "29", name: "SR-090", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-090.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "30", name: "SR-091", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-091.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "31", name: "SR-093", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-093.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "32", name: "SR-094", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-094.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "33", name: "SR-095", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-095.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "34", name: "SR-097", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-097.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "35", name: "SR-098", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-098.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "36", name: "SR-099", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-099.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "37", name: "SR-100", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-100.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "38", name: "SR-101", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-101.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "39", name: "SR-279", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-279.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "40", name: "SR-508", category: "alluminium-doors-windows-gasket", imageUrl: "/shypram-catalogue/product_images/Alluminium Doors and windows gasket/SR-508.png", cuttingQuantity: 0, availability: "in-stock" },

  // Container Gasket (10 products)
  { id: "200", name: "Container Gasket 1", category: "container-gasket", imageUrl: "/shypram-catalogue/product_images/Container Gasket/page_8_product_1.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "201", name: "Container Gasket 2", category: "container-gasket", imageUrl: "/shypram-catalogue/product_images/Container Gasket/page_8_product_2.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "202", name: "Container Gasket 3", category: "container-gasket", imageUrl: "/shypram-catalogue/product_images/Container Gasket/page_8_product_3.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "203", name: "Container Gasket 4", category: "container-gasket", imageUrl: "/shypram-catalogue/product_images/Container Gasket/page_8_product_4.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "204", name: "Container Gasket 5", category: "container-gasket", imageUrl: "/shypram-catalogue/product_images/Container Gasket/page_8_product_5.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "205", name: "Container Gasket 6", category: "container-gasket", imageUrl: "/shypram-catalogue/product_images/Container Gasket/page_8_product_6.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "206", name: "Container Gasket 7", category: "container-gasket", imageUrl: "/shypram-catalogue/product_images/Container Gasket/page_8_product_7.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "207", name: "Container Gasket 8", category: "container-gasket", imageUrl: "/shypram-catalogue/product_images/Container Gasket/page_8_product_8.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "208", name: "Container Gasket 9", category: "container-gasket", imageUrl: "/shypram-catalogue/product_images/Container Gasket/page_8_product_9.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "209", name: "Container Gasket 10", category: "container-gasket", imageUrl: "/shypram-catalogue/product_images/Container Gasket/page_8_product_10.png", cuttingQuantity: 0, availability: "in-stock" },

  // Facade Rubber Gasket (10 products)
  { id: "300", name: "SR-301", category: "facade-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Facade Rubber Gasket/SR-301.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "301", name: "SR-302", category: "facade-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Facade Rubber Gasket/SR-302.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "302", name: "SR-303", category: "facade-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Facade Rubber Gasket/SR-303.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "303", name: "SR-304", category: "facade-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Facade Rubber Gasket/SR-304.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "304", name: "SR-306", category: "facade-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Facade Rubber Gasket/SR-306.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "305", name: "SR-308", category: "facade-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Facade Rubber Gasket/SR-308.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "306", name: "SR-318", category: "facade-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Facade Rubber Gasket/SR-318.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "307", name: "SR-319", category: "facade-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Facade Rubber Gasket/SR-319.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "308", name: "SR-320", category: "facade-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Facade Rubber Gasket/SR-320.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "309", name: "SR-321", category: "facade-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Facade Rubber Gasket/SR-321.png", cuttingQuantity: 0, availability: "in-stock" },

  // Profiles for Aluminium Doors and Windows (19 products)
  { id: "400", name: "Profile 11", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/page_8_product_11.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "401", name: "Profile 12", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/page_8_product_12.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "402", name: "Profile 13", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/page_8_product_13.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "403", name: "SR-666", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-666.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "404", name: "SR-910", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-910.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "405", name: "SR-913", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-913.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "406", name: "SR-916", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-916.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "407", name: "SR-917", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-917.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "408", name: "SR-919", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-919.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "409", name: "SR-920", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-920.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "410", name: "SR-921", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-921.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "411", name: "SR-922", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-922.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "412", name: "SR-924", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-924.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "413", name: "SR-925", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-925.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "414", name: "SR-927", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-927.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "415", name: "SR-928", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-928.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "416", name: "SR-929", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-929.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "417", name: "SR-930", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-930.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "418", name: "SR-931", category: "profiles-alluminium-doors-windows", imageUrl: "/shypram-catalogue/product_images/Profiles for Alluminium Doors and Windows/SR-931.png", cuttingQuantity: 0, availability: "in-stock" },

  // Profiles for U-Clamp & C-Clamp (9 products)
  { id: "500", name: "U-Clamp Profile 1", category: "profiles-u-clamp-c-clamp", imageUrl: "/shypram-catalogue/product_images/Profiles for U_clamp & C_clamp EPDM Rubber & Silicon Rubber/page_7_last_pro.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "501", name: "U-Clamp Profile 2", category: "profiles-u-clamp-c-clamp", imageUrl: "/shypram-catalogue/product_images/Profiles for U_clamp & C_clamp EPDM Rubber & Silicon Rubber/page_7_product_2.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "502", name: "U-Clamp Profile 3", category: "profiles-u-clamp-c-clamp", imageUrl: "/shypram-catalogue/product_images/Profiles for U_clamp & C_clamp EPDM Rubber & Silicon Rubber/page_7_product_3.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "503", name: "U-Clamp Profile 4", category: "profiles-u-clamp-c-clamp", imageUrl: "/shypram-catalogue/product_images/Profiles for U_clamp & C_clamp EPDM Rubber & Silicon Rubber/page_7_product_4.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "504", name: "SR-801", category: "profiles-u-clamp-c-clamp", imageUrl: "/shypram-catalogue/product_images/Profiles for U_clamp & C_clamp EPDM Rubber & Silicon Rubber/SR-801.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "505", name: "SR-804", category: "profiles-u-clamp-c-clamp", imageUrl: "/shypram-catalogue/product_images/Profiles for U_clamp & C_clamp EPDM Rubber & Silicon Rubber/SR-804.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "506", name: "SR-805", category: "profiles-u-clamp-c-clamp", imageUrl: "/shypram-catalogue/product_images/Profiles for U_clamp & C_clamp EPDM Rubber & Silicon Rubber/SR-805.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "507", name: "SR-806", category: "profiles-u-clamp-c-clamp", imageUrl: "/shypram-catalogue/product_images/Profiles for U_clamp & C_clamp EPDM Rubber & Silicon Rubber/SR-806.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "508", name: "SR-911", category: "profiles-u-clamp-c-clamp", imageUrl: "/shypram-catalogue/product_images/Profiles for U_clamp & C_clamp EPDM Rubber & Silicon Rubber/SR-911.png", cuttingQuantity: 0, availability: "in-stock" },

  // Railing Rubber Gasket (40 products)
  { id: "600", name: "SR-401", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-401.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "601", name: "SR-404", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-404.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "602", name: "SR-406", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-406.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "603", name: "SR-407", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-407.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "604", name: "SR-408", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-408.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "605", name: "SR-409", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-409.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "606", name: "SR-412", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-412.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "607", name: "SR-414", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-414.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "608", name: "SR-415", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-415.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "609", name: "SR-422", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-422.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "610", name: "SR-423", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-423.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "611", name: "SR-432", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-432.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "612", name: "SR-433", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-433.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "613", name: "SR-437", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-437.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "614", name: "SR-438", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-438.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "615", name: "SR-439", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-439.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "616", name: "SR-441", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-441.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "617", name: "SR-443", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-443.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "618", name: "SR-446", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-446.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "619", name: "SR-455", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-455.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "620", name: "SR-458", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-458.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "621", name: "SR-461", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-461.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "622", name: "SR-462", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-462.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "623", name: "SR-464", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-464.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "624", name: "SR-465", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-465.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "625", name: "SR-470", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-470.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "626", name: "SR-471", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-471.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "627", name: "SR-472", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-472.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "628", name: "SR-474", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-474.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "629", name: "SR-477", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-477.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "630", name: "SR-479", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-479.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "631", name: "SR-480", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-480.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "632", name: "SR-481", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-481.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "633", name: "SR-482", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-482.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "634", name: "SR-483", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-483.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "635", name: "SR-484", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-484.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "636", name: "SR-486", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-486.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "637", name: "SR-606", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-606.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "638", name: "SR-607", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-607.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "639", name: "SR-608", category: "railing-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Railing Rubber Gasket/SR-608.png", cuttingQuantity: 0, availability: "in-stock" },

  // Sliding and Folding Rubber Gasket (4 products)
  { id: "700", name: "SR-305", category: "sliding-folding-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Sliding and Folding Rubber Gasket/SR-305.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "701", name: "SR-307", category: "sliding-folding-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Sliding and Folding Rubber Gasket/SR-307.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "702", name: "SR-310", category: "sliding-folding-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Sliding and Folding Rubber Gasket/SR-310.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "703", name: "SR-665", category: "sliding-folding-rubber-gasket", imageUrl: "/shypram-catalogue/product_images/Sliding and Folding Rubber Gasket/SR-665.png", cuttingQuantity: 0, availability: "in-stock" },

  // UPVC Door and Window Rubber Gasket (5 products)
  { id: "800", name: "SR-086", category: "upvc-door-window-gasket", imageUrl: "/shypram-catalogue/product_images/UPVC Door and Window Rubber Gasket/SR-086.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "801", name: "SR-092", category: "upvc-door-window-gasket", imageUrl: "/shypram-catalogue/product_images/UPVC Door and Window Rubber Gasket/SR-092.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "802", name: "SR-314", category: "upvc-door-window-gasket", imageUrl: "/shypram-catalogue/product_images/UPVC Door and Window Rubber Gasket/SR-314.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "803", name: "SR-603", category: "upvc-door-window-gasket", imageUrl: "/shypram-catalogue/product_images/UPVC Door and Window Rubber Gasket/SR-603.png", cuttingQuantity: 0, availability: "in-stock" },
  { id: "804", name: "SR-604", category: "upvc-door-window-gasket", imageUrl: "/shypram-catalogue/product_images/UPVC Door and Window Rubber Gasket/SR-604.png", cuttingQuantity: 0, availability: "in-stock" }
]
