import type { Order } from "./types"

export const mockOrders: Order[] = [
  {
    id: "1",
    orderNumber: "ORD-1704123456",
    customerInfo: {
      companyName: "ABC Manufacturing Ltd",
      contactPerson: "John Smith",
      email: "john@abcmfg.com",
      phone: "+91 70169 63340",
      address: "123 Industrial Area, Mumbai, Maharashtra 400001",

    },
    items: [
      {
        productId: "1",
        product: {
          id: "1",
          name: "Standard Door Gasket - Black",
          category: "alluminium-doors-windows-gasket",
          description: "High-quality EPDM rubber door gasket suitable for residential and commercial doors.",
          specifications: ["Material: EPDM Rubber", "Color: Black"],
          imageUrl: "/black-rubber-door-gasket-profile.png",
          pricePerKg: 450,
          minOrderQuantity: 5,
          availability: "in-stock",
          cuttingQuantity: 0,
        },
        cuttingQuantity: 25,
      },
    ],
    packagingOption: "plain",
    finalPackaging: "box",
    totalAmount: 11250,
    status: "pending",
    orderDate: new Date("2024-01-20"),
    estimatedDelivery: new Date("2024-01-27"),
  },
  {
    id: "2",
    orderNumber: "ORD-1704123457",
    customerInfo: {
      companyName: "XYZ Industries",
      contactPerson: "Sarah Johnson",
      email: "sarah@xyzind.com",
      phone: "",
      address: "456 Business Park, Delhi, Delhi 110001",
    },
    items: [
      {
        productId: "2",
        product: {
          id: "2",
          name: "Window Glazing Gasket - Grey",
          category: "upvc-door-window-gasket",
          description: "Weather-resistant glazing gasket for window installations.",
          specifications: ["Material: TPE", "Color: Grey"],
          imageUrl: "/grey-rubber-window-gasket-profile.png",
          pricePerKg: 520,
          minOrderQuantity: 3,
          availability: "in-stock",
          cuttingQuantity: 0,
        },
        cuttingQuantity: 15,
      },
    ],
    packagingOption: "printed",
    finalPackaging: "bag",
    totalAmount: 7800,
    status: "confirmed",
    orderDate: new Date("2024-01-19"),
    estimatedDelivery: new Date("2024-01-26"),
  },
  {
    id: "3",
    orderNumber: "ORD-1704123458",
    customerInfo: {
      companyName: "Tech Solutions Pvt Ltd",
      contactPerson: "Mike Wilson",
      email: "mike@techsol.com",
      phone: "+91 76543 21098",
      address: "789 Tech Hub, Bangalore, Karnataka 560001",

    },
    items: [
      {
        productId: "4",
        product: {
          id: "4",
          name: "Industrial Flange Gasket",
          category: "container-gasket",
          description: "Heavy-duty gasket for industrial flange connections.",
          specifications: ["Material: NBR", "Color: Black"],
          imageUrl: "/black-industrial-flange-gasket-rubber.png",
          pricePerKg: 680,
          minOrderQuantity: 10,
          availability: "in-stock",
          cuttingQuantity: 0,
        },
        cuttingQuantity: 50,
      },
    ],
    packagingOption: "plain",
    finalPackaging: "box",
    totalAmount: 34000,
    status: "processing",
    orderDate: new Date("2024-01-18"),
    estimatedDelivery: new Date("2024-01-25"),
  },
]
