name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: |
        echo "Starting build process..."
        npm run build
        echo "Build completed. Checking output directory..."
        ls -la
        if [ -d "out" ]; then
          echo "Output directory exists:"
          ls -la out/
        else
          echo "Output directory does not exist!"
          exit 1
        fi
    
    - name: Add .nojekyll file
      run: touch ./out/.nojekyll
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out